// Centralized English copy keeps UI and API messages consistent.
const l = {
  metadata: {
    title: 'EmailApp | Remote Programming Companies',
    description:
      'Discover remote programming and IT companies that hire across Europe.',
  },
  landing: {
    appName: 'EmailApp',
    accountNavigation: 'Account navigation',
    signIn: 'Sign in',
    createAccount: 'Create account',
    eyebrow: 'Remote opportunities, without the endless search',
    title: 'Find companies that match your skills.',
    highlight: 'Apply directly.',
    description:
      'Choose your specialization and region to access a focused list of remote employers and company contacts across Europe.',
    primaryAction: 'Create a free account',
    secondaryAction: 'I already have an account',
    proPlan: 'Pro plan',
    comingSoon: 'Coming soon',
    proPrice: '€5',
    perMonth: '/ month',
    proDescription: 'Access up to 2,500 company contacts for direct outreach.',
    footer: 'EmailApp — find remote programming companies across Europe.',
  },
  directory: {
    appName: 'EmailApp',
    eyebrow: 'Remote companies. Direct contacts.',
    heroTitle: 'Choose your specialty.',
    heroHighlight: 'Get up to 200 company emails for direct applications.',
    heroDescription:
      'Filter remote programming employers hiring across Europe and start reaching out in minutes.',
    selectSpecializationPrompt:
      'Choose a specialization to see matching companies and their contact emails.',
    loadError: 'We could not load companies right now. Please try again later.',
    verificationRequiredLabel: 'Email verification required',
    verificationRequiredTitle: 'Verify your email to open the directory',
    verificationRequiredDescription:
      'Use the verification link in your inbox, then return here to access company contacts.',
    footer: 'EmailApp — remote programming companies hiring across Europe.',
  },
  filters: {
    specialization: 'Specialization',
    chooseSpecialization: 'Choose a specialization',
    region: 'Region',
    anyRegion: 'Any region',
    eu: 'EU',
    europe: 'Europe',
    countries: 'Countries',
    submit: 'Show company contacts',
  },
  companies: {
    sectionLabel: 'Companies',
    empty: 'No companies match these filters',
  },
  auth: {
    appName: 'EmailApp',
    signupMetadataTitle: 'Create account | EmailApp',
    signupMetadataDescription:
      'Create an EmailApp account and verify your email address.',
    signupTitle: 'Create your account',
    signupDescription: 'Verify your email to access company contact addresses.',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm password',
    passwordHint: 'Use at least 8 characters.',
    createAccount: 'Create account',
    creatingAccount: 'Creating account...',
    invalidSignupDetails: 'Enter a valid email and a secure password.',
    passwordsDoNotMatch: 'Passwords do not match.',
    accountExists: 'An account with this email already exists.',
    signupSuccess:
      'Account created. Check your inbox to verify your email address.',
    signupFailed: 'We could not create your account. Please try again.',
    loginMetadataTitle: 'Sign in | EmailApp',
    loginMetadataDescription:
      'Sign in to access the EmailApp company directory.',
    loginTitle: 'Welcome back',
    loginDescription: 'Sign in to access remote company contacts.',
    signIn: 'Sign in',
    signingIn: 'Signing in...',
    signOut: 'Sign out',
    signingOut: 'Signing out...',
    noAccount: 'New to EmailApp?',
    createAccountLink: 'Create an account',
    haveAccount: 'Already have an account?',
    signInLink: 'Sign in',
    invalidCredentials: 'Invalid email or password.',
    loginFailed: 'We could not sign you in. Please try again.',
    logoutFailed: 'We could not sign you out. Please try again.',
    sessionFailed: 'We could not check your session. Please try again.',
    authenticationRequired: 'Authentication required.',
    emailVerificationRequired: 'Email verification required.',
    verifyMetadataTitle: 'Verify email | EmailApp',
    verifyMetadataDescription: 'Verify your EmailApp email address.',
    verifyTitle: 'Verify your email',
    verifyDescription:
      'Confirm your email address before accessing company contacts.',
    verifyButton: 'Verify email address',
    verifying: 'Verifying...',
    verificationSuccess: 'Your email address has been verified.',
    invalidVerificationLink: 'This verification link is invalid or expired.',
    verificationFailed: 'We could not verify your email. Please try again.',
    continueToSignIn: 'Continue to sign in',
    backHome: 'Back to home',
  },
} as const;

export default l;
export type Language = typeof l;
